# Generated by Django 3.2.9 on 2021-11-23 15:16

import ProducT.models
import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_descr', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('product_image', models.ImageField(blank=True, default=ProducT.models.get_default_product_image, max_length=255, null=True, upload_to=ProducT.models.get_product_image_filepath)),
                ('product_cost', models.FloatField(default=0)),
                ('product_type', models.CharField(max_length=100)),
                ('product_creator', models.CharField(max_length=50)),
                ('product_video', embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=SlLIEU2e7BA')),
                ('product_file', models.FileField(null=True, upload_to=ProducT.models.product_directory_path)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
