# Generated by Django 3.2.9 on 2021-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProducT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_tiny',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
