# Generated by Django 3.2.5 on 2021-10-31 15:40

import News.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20211031_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_News',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=News.models.upload_location, width_field='width_field'),
        ),
    ]
