# Generated by Django 3.2.9 on 2021-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
