# Generated by Django 3.2.4 on 2021-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizmat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.FileField(default='static\x0cizmat\\Files', upload_to='', verbose_name='Файлы'),
        ),
    ]
