# Generated by Django 3.2.5 on 2021-08-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fizmat', '0002_article_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='files',
        ),
    ]
